name: Playwright Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  playwright_test:
    name: Playwright Test
    env:
      # Fix Firefox crash in GitHub Actions
      # Details: https://github.com/microsoft/playwright/issues/6500#issuecomment-838515115
      HOME: /root
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # specified container to use for the job to not download browsers on every run. Need to be updated with playwright version
    container: mcr.microsoft.com/playwright:v1.52.0-noble
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}  --reporter=blob,list
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  reporting:
    if: ${{ always() }}
    needs: playwright_test
    name: Reporting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      - name: Install dependencies
        run: npm ci
      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        id: upload_report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report
          retention-days: 14
      - name: Summary
        id: summary
        run: |
          echo '## 📝 Playwright HTML report' >> "$GITHUB_STEP_SUMMARY"
          echo '[Download / view report](${{ steps.upload_report.outputs.artifact-url }})' >> "$GITHUB_STEP_SUMMARY"
