name: Playwright Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  playwright_test:
    name: Playwright Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 30

  reporting:
    if: ${{ always() }}
    needs: playwright_test
    name: Reporting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          merge-multiple: true
          path: playwright-reports
      - name: Install dependencies
        run: npm ci
      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./playwright-reports
      - name: Upload Final HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-playwright-report
          path: playwright-report/
      - name: Summary
        run: |
          echo "## [Playwright HTML Report](./playwright-report/index.html)" >> $GITHUB_STEP_SUMMARY
